### ISSUE TITLE
Mobile Client Options Cutoff. 

### ISSUE THREAD

**Issue by DrMkdaddy** [tedhinklater/finimalism#17]
The word "Dashboard" is cut off making the whole thing look a little strange and is it possible to have some dividers between the elements in the settings menu? 

![Screenshot_20241118_032317_Jellyfin.jpg](https://github.com/user-attachments/assets/d38c82b7-4a2f-431b-9869-1cb410cd76e0)

**Comment by tedhinklater** [comment]
![Screenshot 2024-11-18 120837](https://github.com/user-attachments/assets/f285afe5-200e-488d-986c-60bfa12911dd)

fixed in the update, add this if you want the fix immediately


#myPreferencesMenuPage .sectionTitle {text-decoration: underline;}
#myPreferencesPage .readOnlycontent {font-size: 90%;}
#myPreferencesMenuPage .verticalSection-extrabottompadding .emby-button .listItem {justify-content: center;}
#myPreferencesMenuPage .verticalSection-extrabottompadding .emby-button .listItemBody {overflow: visible;text-overflow: unset;white-space: wrap;padding-right: 0.75em;}
#myPreferencesMenuPage .verticalSection-extrabottompadding .emby-button .listItemBodyText {text-overflow: visible !important;}
