### ISSUE TITLE
"Continue watching" is misaligned on moblie

### ISSUE THREAD

**Issue by felixschndr** [tedhinklater/finimalism#3]
First of all: Thank you for creating this awesome theme! I think it looks great.

There is one minor thing: On mobile the `continue watching` text (in my language `Weiterschauen`) is misaligned as you can see here:
![Screenshot_20240528_200232_Jellyfin](https://github.com/tedhinklater/finimalism/assets/45742226/37750ee9-37a7-4a0c-b414-5edfe328c07e)
It is not above the images as in the other rows.

I was wondering if you could fix this, I'd be happy to help test if necessary =)

P.S. I was wondering about increasing the text size under the images slightly. I think it is a bit too small. What do you think about this?

**Comment by tedhinklater** [comment]
Hello mate, I set the "Continue Watching" section on the same row, instead of above, because a) there is usually only 1 or 2 items there so horizontal space is not an issue, and b) it provides more vertical space, allowing you to see three rows of content without having to scroll down. If you would prefer to have it aligned as you mentioned, copy the full css at https://cdn.jsdelivr.net/gh/tedhinklater/finimalism@main/finimalism6-0.css and remove these 2 snippets:

`/* Apply flex display style only to the Continue Watching section in the home page */
.homePage .section1.verticalSection {
    display: flex;
    flex-direction: row;
    align-items: center;
}

/* Push "Continue Watching" header to the left */
.homePage .section1.verticalSection .sectionTitle-cards {
    margin-right: 10px;
    margin-left: 10px;
}`

I do agree the text is very small, I'll increase the size a little! I'm glad you enjoyed the theme, hope you are having a good night.

**Comment by tedhinklater** [comment]
Fixed for mobile
![ss1](https://github.com/tedhinklater/finimalism/assets/66086488/c23281ef-8e5b-4ea5-92a8-4d61a9f1b88f)

**Comment by felixschndr** [comment]
Looks good, I like it! Thank you very much

**Comment by felixschndr** [comment]
@tedhinklater Since some update (I am not sure which one) the issue seems to appear again, but on web this time:
![image](https://github.com/tedhinklater/finimalism/assets/45742226/a9e3e27f-97ae-4197-92f4-318292c1448a)
It looks good on mobile:
![Screenshot_20240601_114651_Jellyfin](https://github.com/tedhinklater/finimalism/assets/45742226/82f4c907-56b3-431e-947d-7a81c843db9e)

**Comment by tedhinklater** [comment]
Hey are you using the new code? https://github.com/tedhinklater/finimalism/blob/main/finimalism7.css 

The last one we used was finimalism6, with a custom theme.css, but 7 uses the [original theme.css](https://github.com/tedhinklater/finimalism/blob/main/theme.css)

**Comment by tedhinklater** [comment]
I've reverted it to be the same as mobile.

**Comment by felixschndr** [comment]
> Hey are you using the new code? https://github.com/tedhinklater/finimalism/blob/main/finimalism7.css
> 
> The last one we used was finimalism6, with a custom theme.css, but 7 uses the [original theme.css](https://github.com/tedhinklater/finimalism/blob/main/theme.css)

Yes, I am.

----

> I've reverted it to be the same as mobile.

Thank you very much! Now it looks good on both platforms.
